[colors]
foreground = "#cacaca"
background = "#24283b"
cursor_bg = "#cacaca"
cursor_border = "#cacaca"
cursor_fg = "#24283b"
selection_bg = "#2e3c64"
selection_fg = "#cacaca"
split = "#368aec"
compose_cursor = "#ffc07a"
scrollbar_thumb = "#292e42"

ansi = ["#000000", "#f3505c", "#51f66f", "#eedb85", "#368aec", "#b5b6e3", "#00f0ff", "#a9b1d6"]
brights = ["#414868", "#f3505c", "#51f66f", "#eedb85", "#368aec", "#b5b6e3", "#00f0ff", "#cacaca"]

[colors.tab_bar]
inactive_tab_edge = "#1f2335"
background = "#24283b"

[colors.tab_bar.active_tab]
fg_color = "#1f2335"
bg_color = "#368aec"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#368aec"
bg_color = "#292e42"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#368aec"
bg_color = "#24283b"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#368aec"
bg_color = "#24283b"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_storm"