[colors]
foreground = "#2d2d2d"
background = "#e1e2e7"
cursor_bg = "#2d2d2d"
cursor_border = "#2d2d2d"
cursor_fg = "#e1e2e7"
selection_bg = "#b6bfe2"
selection_fg = "#2d2d2d"
split = "#2666b1"
compose_cursor = "#3f2700"
scrollbar_thumb = "#c4c8da"

ansi = ["#e9e9ed", "#c02434", "#07290c", "#252110", "#2666b1", "#2f327c", "#00272a", "#343f64"]
brights = ["#a1a6c5", "#c02434", "#07290c", "#252110", "#2666b1", "#2f327c", "#00272a", "#2d2d2d"]

[colors.tab_bar]
inactive_tab_edge = "#e9e9ec"
background = "#e1e2e7"

[colors.tab_bar.active_tab]
fg_color = "#e9e9ec"
bg_color = "#2666b1"

[colors.tab_bar.inactive_tab]
fg_color = "#8990b3"
bg_color = "#c4c8da"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#2666b1"
bg_color = "#c4c8da"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#2666b1"
bg_color = "#e1e2e7"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#2666b1"
bg_color = "#e1e2e7"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_day"