# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#24283b'
foreground = '#cacaca'

#[colors.cursor]
#cursor = '#cacaca'
#text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f3505c'
green = '#51f66f'
yellow = '#eedb85'
blue = '#368aec'
magenta = '#b5b6e3'
cyan = '#00f0ff'
white = '#000000'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f3505c'
green = '#51f66f'
yellow = '#eedb85'
blue = '#368aec'
magenta = '#b5b6e3'
cyan = '#00f0ff'
white = '#cacaca'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ffc07a'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

