attribute = { fg = "#8a5b00" }
comment = { fg = "#777777", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#8c6c3e" }
constant = { fg = "#1e6b2c" }
"constant.builtin" = { fg = "#555501" }
"constant.builtin.boolean" = { fg = "#6d691a" }
"constant.character" = { fg = "#d35fc1" }
"constant.character.escape" = { fg = "#9854f1" }
"constant.numeric" = { fg = "#2666b1" }
"constant.numeric.float" = { fg = "#2666b1" }
"constant.numeric.integer" = { fg = "#2666b1" }
constructor = { fg = "#c02434" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#506d9c" }
"diff.delta.moved" = { fg = "#2e7de9" }
"diff.minus" = { fg = "#c47981" }
"diff.plus" = { fg = "#4197a4" }
error = { fg = "#c64343" }
function = { fg = "#00676e" }
"function.builtin" = { fg = "#555501" }
"function.macro" = { fg = "#6d691a" }
"function.method" = 
"function.special" = { fg = "#8a5b00" }
hint = { fg = "#118c74" }
info = { fg = "#07879d" }
keyword = { fg = "#7847bd", modifiers = ["italic"] }
"keyword.control" = { fg = "#c02434" }
"keyword.control.conditional" = { fg = "#c02434" }
"keyword.control.exception" = { fg = "#c02434" }
"keyword.control.repeat" = { fg = "#c02434" }
"keyword.control.return" = { fg = "#7847bd", modifiers = ["italic"] }
"keyword.directive" = { fg = "#8a5b00" }
"keyword.function" = { fg = "#9854f1" }
"keyword.operator" = { fg = "#c02434" }
label = { fg = "#2e7de9" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#e9e9ec", fg = "#3760bf" }
"markup.heading.hover" = { bg = "#b3b8d1" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#2e7de9", underline = { style = "line" } }
"markup.link.label" = { fg = "#118c74" }
"markup.link.text" = { fg = "#118c74" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#b15c00", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#777777" }
"markup.normal.hover" = { fg = "#6172b0" }
"markup.raw" = { fg = "#118c74" }
"markup.raw.block" = { fg = "#118c74" }
"markup.raw.inline" = { bg = "#a1a6c5", fg = "#2e7de9" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#c02434" }
special = { fg = "#555501" }
string = { fg = "#645c35" }
"string.regexp" = { fg = "#2e5857" }
"string.special" = { fg = "#e80000" }
tag = { fg = "#c02434" }
type = { fg = "#c02434" }
"type.builtin" = { fg = "#2496ac" }
"type.enum" = { fg = "#c02434" }
"type.enum.variant" = { fg = "#1e6b2c" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#3760bf", fg = "#e1e2e7" }
"ui.cursor.match" = { fg = "#b15c00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#a8aecb" }
"ui.linenr.select" = { fg = "#68709a" }
"ui.menu" = { bg = "#e9e9ec", fg = "#3760bf" }
"ui.menu.scroll" = { bg = 14211292, fg = 11054795 }
"ui.menu.selected" = { bg = "#b3b8d1" }
"ui.popup" = { bg = "#e9e9ec", fg = "#2496ac" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#e9e9ec", fg = "#6172b0" }
"ui.statusline.inactive" = { bg = "#e9e9ec", fg = "#a8aecb" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { fg = "#3760bf" }
"ui.text.focus" = { bg = "#b6bfe2" }
"ui.text.inactive" = { fg = "#777777", modifiers = ["italic"] }
"ui.text.info" = { bg = "#e9e9ec", fg = "#3760bf" }
"ui.virtual.inlay-hint" = { bg = "#acd7eb", fg = "#118c74" }
"ui.window" = { fg = "#e9e9ed", modifiers = ["bold"] }
variable = { fg = "#3760bf" }
"variable.builtin" = { fg = "#f52a65" }
"variable.other.member" = { fg = "#387068" }
"variable.parameter" = { fg = "#8c6c3e" }
warning = { fg = "#8c6c3e" }

[palette]
bg = "#e1e2e7"
bg_dark = "#e9e9ec"
bg_float = "#e9e9ec"
bg_highlight = "#c4c8da"
bg_popup = "#e9e9ec"
bg_search = "#7890dd"
bg_sidebar = "#e9e9ec"
bg_statusline = "#e9e9ec"
bg_visual = "#b6bfe2"
black = "#e9e9ed"
blue = "#2e7de9"
blue0 = "#7890dd"
blue1 = "#188092"
blue2 = "#07879d"
blue5 = "#006a83"
blue6 = "#2e5857"
blue7 = "#92a6d5"
border = "#e9e9ed"
border_highlight = "#2496ac"
comment = "#777777"
cyan = "#007197"
cyber_black_transparent = "#ffffff"
cyber_blue = "#2666b1"
cyber_cyan = "#00676e"
cyber_cyan_light = "#005c55"
cyber_green = "#1e731e"
cyber_green_light = "#006200"
cyber_grey = "#777777"
cyber_grey_light = "#5b5b5b"
cyber_kaki = "#6d691a"
cyber_neon_green = "#1e6b2c"
cyber_orange_light = "#8a5b00"
cyber_pink = "#d35fc1"
cyber_pure_white = "#4f4f4f"
cyber_purple_dark = "#826493"
cyber_purple_light = "#646b97"
cyber_purple_normal = "#6467c0"
cyber_red = "#c02434"
cyber_red_dark = "#d1a9ab"
cyber_red_error = "#e00000"
cyber_red_light = "#e80000"
cyber_white = "#666666"
cyber_yellow = "#555501"
cyber_yellow_light = "#645c35"
dark3 = "#8990b3"
dark5 = "#68709a"
"delta.add" = "#57a7bc"
"delta.delete" = "#d99ea2"
"diff.add" = "#aecde6"
"diff.change" = "#d6d8e3"
"diff.delete" = "#dfccd4"
"diff.text" = "#92a6d5"
error = "#c64343"
fg = "#3760bf"
fg_dark = "#6172b0"
fg_float = "#3760bf"
fg_gutter = "#a8aecb"
fg_sidebar = "#6172b0"
"git.add" = "#4197a4"
"git.change" = "#506d9c"
"git.delete" = "#c47981"
"git.ignore" = "#8990b3"
"gitSigns.add" = "#399a96"
"gitSigns.change" = "#6482bd"
"gitSigns.delete" = "#c25d64"
green = "#587539"
green1 = "#387068"
green2 = "#38919f"
hint = "#118c74"
info = "#07879d"
magenta = "#9854f1"
magenta2 = "#d20065"
orange = "#b15c00"
purple = "#7847bd"
red = "#f52a65"
red1 = "#c64343"
teal = "#118c74"
terminal_black = "#a1a6c5"
todo = "#2e7de9"
warning = "#8c6c3e"
yellow = "#8c6c3e"