attribute = { fg = "#ffc07a" }
comment = { fg = "#777777", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#eedb85" }
constant = { fg = "#51f66f" }
"constant.builtin" = { fg = "#00f0ff" }
"constant.builtin.boolean" = { fg = "#908b25" }
"constant.character" = { fg = "#eedb85" }
"constant.character.escape" = { fg = "#b5b6e3" }
"constant.numeric" = { fg = "#368aec" }
"constant.numeric.float" = { fg = "#368aec" }
"constant.numeric.integer" = { fg = "#368aec" }
constructor = { fg = "#f3505c" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#6183bb" }
"diff.delta.moved" = { fg = "#368aec" }
"diff.minus" = { fg = "#914c54" }
"diff.plus" = { fg = "#449dab" }
error = { fg = "#db4b4b" }
function = { fg = "#00f0ff" }
"function.builtin" = { fg = "#00f0ff" }
"function.macro" = { fg = "#908b25" }
"function.method" = 
"function.special" = { fg = "#ffc07a" }
hint = { fg = "#1abc9c" }
info = { fg = "#0db9d7" }
keyword = { fg = "#f3505c", modifiers = ["italic"] }
"keyword.control" = { fg = "#f3505c" }
"keyword.control.conditional" = { fg = "#f3505c" }
"keyword.control.exception" = { fg = "#f3505c" }
"keyword.control.repeat" = { fg = "#f3505c" }
"keyword.control.return" = { fg = "#f3505c", modifiers = ["italic"] }
"keyword.directive" = { fg = "#ffc07a" }
"keyword.function" = { fg = "#00f0ff" }
"keyword.operator" = { fg = "#f3505c" }
label = { fg = "#00f0ff" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#16161e", fg = "#cacaca" }
"markup.heading.hover" = { bg = "#343a55" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#368aec", underline = { style = "line" } }
"markup.link.label" = { fg = "#1abc9c" }
"markup.link.text" = { fg = "#1abc9c" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#ffc07a", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#777777" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#1abc9c" }
"markup.raw.block" = { fg = "#1abc9c" }
"markup.raw.inline" = { bg = "#414868", fg = "#368aec" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#f3505c" }
special = { fg = "#00f0ff" }
string = { fg = "#eedb85" }
"string.regexp" = { fg = "#368aec" }
"string.special" = { fg = "#d867c6" }
tag = { fg = "#f3505c" }
type = { fg = "#f3505c" }
"type.builtin" = { fg = "#f3505c" }
"type.enum" = { fg = "#f3505c" }
"type.enum.variant" = { fg = "#51f66f" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#cacaca", fg = "#1a1b26" }
"ui.cursor.match" = { fg = "#ffc07a", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3b4261" }
"ui.linenr.select" = { fg = "#737aa2" }
"ui.menu" = { bg = "#16161e", fg = "#cacaca" }
"ui.menu.scroll" = { bg = 2236969, fg = 3883617 }
"ui.menu.selected" = { bg = "#343a55" }
"ui.popup" = { fg = "#27a1b9" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#16161e", fg = "#a9b1d6" }
"ui.statusline.inactive" = { bg = "#16161e", fg = "#3b4261" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { fg = "#cacaca" }
"ui.text.focus" = { bg = "#283457" }
"ui.text.inactive" = { fg = "#777777", modifiers = ["italic"] }
"ui.text.info" = { fg = "#cacaca" }
"ui.virtual.inlay-hint" = { bg = "#1a2b32", fg = "#1abc9c" }
"ui.window" = { fg = "#15161e", modifiers = ["bold"] }
variable = { fg = "#cacaca" }
"variable.builtin" = { fg = "#f3505c" }
"variable.other.member" = { fg = "#9373a5" }
"variable.parameter" = { fg = "#cacaca" }
warning = { fg = "#eedb85" }

[palette]
bg = "#1a1b26"
bg_dark = "#16161e"
bg_float = "NONE"
bg_highlight = "#292e42"
bg_popup = "#16161e"
bg_search = "#3d59a1"
bg_sidebar = "NONE"
bg_statusline = "#16161e"
bg_visual = "#283457"
black = "#15161e"
blue = "#368aec"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
border = "#15161e"
border_highlight = "#27a1b9"
comment = "#777777"
cyan = "#00f0ff"
dark3 = "#545c7e"
dark5 = "#737aa2"
"delta.add" = "#2c5a66"
"delta.delete" = "#713137"
"diff.add" = "#20303b"
"diff.change" = "#1f2231"
"diff.delete" = "#37222c"
"diff.text" = "#394b70"
error = "#db4b4b"
fg = "#cacaca"
fg_dark = "#a9b1d6"
fg_float = "#cacaca"
fg_gutter = "#3b4261"
fg_sidebar = "#a9b1d6"
"git.add" = "#449dab"
"git.change" = "#6183bb"
"git.delete" = "#914c54"
"git.ignore" = "#545c7e"
"gitSigns.add" = "#266d6a"
"gitSigns.change" = "#536c9e"
"gitSigns.delete" = "#b2555b"
green = "#51f66f"
green1 = "#73daca"
green2 = "#41a6b5"
hint = "#1abc9c"
info = "#0db9d7"
kaki = "#908b25"
magenta = "#b5b6e3"
magenta2 = "#ff007c"
orange = "#ffc07a"
pink = "#d867c6"
purple = "#9373a5"
red = "#f3505c"
red1 = "#db4b4b"
teal = "#1abc9c"
terminal_black = "#414868"
todo = "#368aec"
warning = "#eedb85"
yellow = "#eedb85"