attribute = { fg = "#8a5b00" }
comment = { fg = "#777777", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#645c35" }
constant = { fg = "#1e6b2c" }
"constant.builtin" = { fg = "#c02434" }
"constant.builtin.boolean" = { fg = "#6d691a" }
"constant.character" = { fg = "#d35fc1" }
"constant.character.escape" = { fg = "#6467c0" }
"constant.numeric" = { fg = "#2666b1" }
"constant.numeric.float" = { fg = "#2666b1" }
"constant.numeric.integer" = { fg = "#2666b1" }
constructor = { fg = "#c02434" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#506d9c" }
"diff.delta.moved" = { fg = "#2666b1" }
"diff.minus" = { fg = "#c47981" }
"diff.plus" = { fg = "#4197a4" }
error = { fg = "#c64343" }
function = { fg = "#00676e" }
"function.builtin" = { fg = "#c02434" }
"function.macro" = { fg = "#6d691a" }
"function.method" = 
"function.special" = { fg = "#8a5b00" }
hint = { fg = "#118c74" }
info = { fg = "#07879d" }
keyword = { fg = "#00676e", modifiers = ["italic"] }
"keyword.control" = { fg = "#c02434" }
"keyword.control.conditional" = { fg = "#c02434" }
"keyword.control.exception" = { fg = "#c02434" }
"keyword.control.repeat" = { fg = "#c02434" }
"keyword.control.return" = { fg = "#00676e", modifiers = ["italic"] }
"keyword.directive" = { fg = "#8a5b00" }
"keyword.function" = { fg = "#00676e" }
"keyword.operator" = { fg = "#c02434" }
label = { fg = "#c02434" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#e9e9ec", fg = "#666666" }
"markup.heading.hover" = { bg = "#b3b8d1" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#2666b1", underline = { style = "line" } }
"markup.link.label" = { fg = "#118c74" }
"markup.link.text" = { fg = "#118c74" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#8a5b00", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#777777" }
"markup.normal.hover" = { fg = "#6172b0" }
"markup.raw" = { fg = "#118c74" }
"markup.raw.block" = { fg = "#118c74" }
"markup.raw.inline" = { bg = "#a1a6c5", fg = "#2666b1" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#c02434" }
special = { fg = "#c02434" }
string = { fg = "#645c35" }
"string.regexp" = { fg = "#2666b1" }
"string.special" = { fg = "#c02434" }
tag = { fg = "#c02434" }
type = { fg = "#c02434" }
"type.builtin" = { fg = "#c02434" }
"type.enum" = { fg = "#c02434" }
"type.enum.variant" = { fg = "#1e6b2c" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#666666", fg = "#e1e2e7" }
"ui.cursor.match" = { fg = "#8a5b00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#a8aecb" }
"ui.linenr.select" = { fg = "#68709a" }
"ui.menu" = { bg = "#e9e9ec", fg = "#666666" }
"ui.menu.scroll" = { bg = 14211292, fg = 11054795 }
"ui.menu.selected" = { bg = "#b3b8d1" }
"ui.popup" = { bg = "#e9e9ec", fg = "#2496ac" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#e9e9ec", fg = "#6172b0" }
"ui.statusline.inactive" = { bg = "#e9e9ec", fg = "#a8aecb" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { fg = "#666666" }
"ui.text.focus" = { bg = "#b6bfe2" }
"ui.text.inactive" = { fg = "#777777", modifiers = ["italic"] }
"ui.text.info" = { bg = "#e9e9ec", fg = "#666666" }
"ui.virtual.inlay-hint" = { bg = "#acd7eb", fg = "#118c74" }
"ui.window" = { fg = "#e9e9ed", modifiers = ["bold"] }
variable = { fg = "#666666" }
"variable.builtin" = { fg = "#00676e" }
"variable.other.member" = { fg = "#826493" }
"variable.parameter" = { fg = "#666666" }
warning = { fg = "#645c35" }

[palette]
bg = "#e1e2e7"
bg_dark = "#e9e9ec"
bg_float = "#e9e9ec"
bg_highlight = "#c4c8da"
bg_popup = "#e9e9ec"
bg_search = "#7890dd"
bg_sidebar = "#e9e9ec"
bg_statusline = "#e9e9ec"
bg_visual = "#b6bfe2"
black = "#e9e9ed"
blue = "#2666b1"
blue0 = "#7890dd"
blue1 = "#188092"
blue2 = "#07879d"
blue5 = "#006a83"
blue6 = "#2e5857"
blue7 = "#92a6d5"
border = "#e9e9ed"
border_highlight = "#2496ac"
comment = "#777777"
cyan = "#00676e"
dark3 = "#8990b3"
dark5 = "#68709a"
"delta.add" = "#57a7bc"
"delta.delete" = "#d99ea2"
"diff.add" = "#aecde6"
"diff.change" = "#d6d8e3"
"diff.delete" = "#dfccd4"
"diff.text" = "#92a6d5"
error = "#c64343"
fg = "#666666"
fg_dark = "#6172b0"
fg_float = "#666666"
fg_gutter = "#a8aecb"
fg_sidebar = "#6172b0"
"git.add" = "#4197a4"
"git.change" = "#506d9c"
"git.delete" = "#c47981"
"git.ignore" = "#8990b3"
"gitSigns.add" = "#399a96"
"gitSigns.change" = "#6482bd"
"gitSigns.delete" = "#c25d64"
green = "#1e6b2c"
green1 = "#387068"
green2 = "#38919f"
hint = "#118c74"
info = "#07879d"
kaki = "#6d691a"
magenta = "#6467c0"
magenta2 = "#d20065"
orange = "#8a5b00"
pink = "#d35fc1"
purple = "#826493"
red = "#c02434"
red1 = "#c64343"
teal = "#118c74"
terminal_black = "#a1a6c5"
todo = "#2666b1"
warning = "#645c35"
yellow = "#645c35"