attribute = { fg = "#3f2700" }
comment = { fg = "#777777", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#252110" }
constant = { fg = "#07290c" }
"constant.builtin" = { fg = "#00272a" }
"constant.builtin.boolean" = { fg = "#6d691a" }
"constant.character" = { fg = "#252110" }
"constant.character.escape" = { fg = "#2f327c" }
"constant.numeric" = { fg = "#2666b1" }
"constant.numeric.float" = { fg = "#2666b1" }
"constant.numeric.integer" = { fg = "#2666b1" }
constructor = { fg = "#c02434" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#506d9c" }
"diff.delta.moved" = { fg = "#2666b1" }
"diff.minus" = { fg = "#c47981" }
"diff.plus" = { fg = "#2a6670" }
error = { fg = "#c64343" }
function = { fg = "#00272a" }
"function.builtin" = { fg = "#00272a" }
"function.macro" = { fg = "#6d691a" }
"function.method" = 
"function.special" = { fg = "#3f2700" }
hint = { fg = "#065545" }
info = { fg = "#02505e" }
keyword = { fg = "#c02434", modifiers = ["italic"] }
"keyword.control" = { fg = "#c02434" }
"keyword.control.conditional" = { fg = "#c02434" }
"keyword.control.exception" = { fg = "#c02434" }
"keyword.control.repeat" = { fg = "#c02434" }
"keyword.control.return" = { fg = "#c02434", modifiers = ["italic"] }
"keyword.directive" = { fg = "#3f2700" }
"keyword.function" = { fg = "#00272a" }
"keyword.operator" = { fg = "#c02434" }
label = { fg = "#00272a" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#e9e9ec", fg = "#2d2d2d" }
"markup.heading.hover" = { bg = "#b3b8d1" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#2666b1", underline = { style = "line" } }
"markup.link.label" = { fg = "#065545" }
"markup.link.text" = { fg = "#065545" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#3f2700", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#777777" }
"markup.normal.hover" = { fg = "#343f64" }
"markup.raw" = { fg = "#065545" }
"markup.raw.block" = { fg = "#065545" }
"markup.raw.inline" = { bg = "#a1a6c5", fg = "#2666b1" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#c02434" }
special = { fg = "#00272a" }
string = { fg = "#252110" }
"string.regexp" = { fg = "#2666b1" }
"string.special" = { fg = "#903f83" }
tag = { fg = "#c02434" }
type = { fg = "#c02434" }
"type.builtin" = { fg = "#c02434" }
"type.enum" = { fg = "#c02434" }
"type.enum.variant" = { fg = "#07290c" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#2d2d2d", fg = "#e1e2e7" }
"ui.cursor.match" = { fg = "#3f2700", modifiers = ["bold"] }
"ui.linenr" = { fg = "#a8aecb" }
"ui.linenr.select" = { fg = "#68709a" }
"ui.menu" = { bg = "#e9e9ec", fg = "#2d2d2d" }
"ui.menu.scroll" = { bg = 14211292, fg = 11054795 }
"ui.menu.selected" = { bg = "#b3b8d1" }
"ui.popup" = { bg = "#e9e9ec", fg = "#156474" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#e9e9ec", fg = "#343f64" }
"ui.statusline.inactive" = { bg = "#e9e9ec", fg = "#a8aecb" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { fg = "#2d2d2d" }
"ui.text.focus" = { bg = "#b6bfe2" }
"ui.text.inactive" = { fg = "#777777", modifiers = ["italic"] }
"ui.text.info" = { bg = "#e9e9ec", fg = "#2d2d2d" }
"ui.virtual.inlay-hint" = { bg = "#acd7eb", fg = "#065545" }
"ui.window" = { fg = "#e9e9ed", modifiers = ["bold"] }
variable = { fg = "#2d2d2d" }
"variable.builtin" = { fg = "#c02434" }
"variable.other.member" = { fg = "#826493" }
"variable.parameter" = { fg = "#2d2d2d" }
warning = { fg = "#252110" }

[palette]
bg = "#e1e2e7"
bg_dark = "#e9e9ec"
bg_float = "#e9e9ec"
bg_highlight = "#c4c8da"
bg_popup = "#e9e9ec"
bg_search = "#7890dd"
bg_sidebar = "#e9e9ec"
bg_statusline = "#e9e9ec"
bg_visual = "#b6bfe2"
black = "#e9e9ed"
blue = "#2666b1"
blue0 = "#7890dd"
blue1 = "#094752"
blue2 = "#02505e"
blue5 = "#002c38"
blue6 = "#081717"
blue7 = "#92a6d5"
border = "#e9e9ed"
border_highlight = "#156474"
comment = "#777777"
cyan = "#00272a"
dark3 = "#8990b3"
dark5 = "#68709a"
"delta.add" = "#57a7bc"
"delta.delete" = "#d99ea2"
"diff.add" = "#aecde6"
"diff.change" = "#d6d8e3"
"diff.delete" = "#dfccd4"
"diff.text" = "#92a6d5"
error = "#c64343"
fg = "#2d2d2d"
fg_dark = "#343f64"
fg_float = "#2d2d2d"
fg_gutter = "#a8aecb"
fg_sidebar = "#343f64"
"git.add" = "#2a6670"
"git.change" = "#506d9c"
"git.delete" = "#c47981"
"git.ignore" = "#8990b3"
"gitSigns.add" = "#399a96"
"gitSigns.change" = "#6482bd"
"gitSigns.delete" = "#c25d64"
green = "#07290c"
green1 = "#16342f"
green2 = "#225f68"
hint = "#065545"
info = "#02505e"
kaki = "#6d691a"
magenta = "#2f327c"
magenta2 = "#d20065"
orange = "#3f2700"
pink = "#903f83"
purple = "#826493"
red = "#c02434"
red1 = "#c64343"
teal = "#065545"
terminal_black = "#a1a6c5"
todo = "#2666b1"
warning = "#252110"
yellow = "#252110"